"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { AuthProvider } from "./context/AuthContext";
import { usePathname } from "next/navigation";
// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  console.log(pathname);
  // Exclude styles for a specific page
  const isExcludedPage = pathname === "/chatbot";
  
  return (
    
    <AuthProvider>
    <html lang="en">
      <body className={isExcludedPage ? "" : "bg-gradient-to-r from-pink-300 to-blue-300"}>
        {children}
      </body>
    </html>
    </AuthProvider>
  );
  
}

